version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - run:
          name: Install pytest
          command: pip install pytest
          
      - run:
          name: Create test-results directory
          command: mkdir -p test-results

      - run:
          name: Run tests and store results
          command: pytest --junitxml=test-results/junit.xml TestGitHubApi.py

      - store_test_results:
          path: test-results

workflows:
  testing_triangles:
    jobs:
      - build-and-test
